In [1]:
import matplotlib.pyplot as plt

In [2]:
from sklearn.linear_model import LogisticRegression

In [3]:
from sklearn.model_selection import train_test_split, StratifiedKFold

In [4]:
import numpy as np

In [5]:
from sklearn.utils import shuffle

In [6]:
from res.t3_aux import poly_16features, create_plot

***Load data***

In [7]:
data = np.loadtxt("res/data.txt",delimiter=',')

***Shuffle data***

In [8]:
np.random.shuffle(data)

In [9]:
Ys = data[:,(0)]

In [10]:
Ys

array([1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1.,
       0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1.,
       1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 1., 0.])

In [11]:
Xs = data[:,1:]

In [12]:
means = np.mean(Xs,axis=0)

In [13]:
stdevs = np.std(Xs,axis=0)

In [14]:
Xs = (Xs-means)/stdevs

In [15]:
Xs

array([[ 0.35741778,  0.77926786],
       [ 0.98809849,  2.29640764],
       [ 0.94463878, -0.83294895],
       [ 0.15165356, -1.15564418],
       [ 0.69129545, -0.55118093],
       [ 0.60952528, -1.22396111],
       [-1.42195866, -1.39113298],
       [-0.17089575, -0.41832495],
       [ 0.27297   ,  0.45877641],
       [ 0.13496997,  1.36137856],
       [ 1.33062691,  0.61870731],
       [ 1.40168662,  0.42697912],
       [ 0.09871922,  0.94014323],
       [ 1.37264482,  1.33902601],
       [ 0.74505367, -0.56282944],
       [-0.62938539,  0.07374592],
       [-1.33030193, -0.58958953],
       [ 1.37841199,  0.40934895],
       [ 0.50880586,  0.59352134],
       [-0.44174655, -0.23194878],
       [-1.42546016, -0.8168929 ],
       [-1.19230191, -1.71729127],
       [ 0.00335503, -0.95730467],
       [ 1.01096118, -0.63712805],
       [-1.49157659, -1.22679454],
       [ 0.85833727, -1.03601082],
       [-0.05905394, -0.83924545],
       [-1.28663625,  1.05536904],
       [ 1.29396421,

In [16]:
Xs = poly_16features(Xs)

In [17]:
Xs

array([[ 3.57417776e-01,  7.79267859e-01,  2.78524185e-01, ...,
         7.75757217e-02,  5.83284908e-03,  2.87364967e-01],
       [ 9.88098486e-01,  2.29640764e+00,  2.26907691e+00, ...,
         5.14871004e+00,  9.41892134e-01,  6.38623530e+01],
       [ 9.44638777e-01, -8.32948953e-01, -7.86835880e-01, ...,
         6.19110702e-01,  7.52192236e-01, -4.00951583e-01],
       ...,
       [-1.53853779e+00,  3.27809373e-01, -5.04347108e-01, ...,
         2.54366005e-01, -8.62066640e+00,  3.78535692e-03],
       [-9.71501866e-01,  2.94752789e-01, -2.86352885e-01, ...,
         8.19979747e-02, -8.65402602e-01,  2.22479304e-03],
       [ 9.66595199e-02, -7.61483767e-01, -7.36046553e-02, ...,
         5.41764529e-03,  8.43768229e-06, -2.56037306e-01]])

In [18]:
X_r,X_t,Y_r,Y_t = train_test_split(Xs, Ys, test_size=0.33, stratify = Ys)

In [19]:
X_r

array([[ 1.07192835e+00, -8.77591082e-02, -9.40714763e-02,
         1.14903039e+00,  7.70166108e-03,  1.23167826e+00,
        -6.75890908e-04, -1.00837883e-01,  8.25562887e-03,
         1.32027084e+00,  5.93155833e-05, -1.08090985e-01,
        -7.24506627e-04,  8.84944265e-03,  1.41523575e+00,
        -5.20548270e-06],
       [ 1.46965678e+00,  7.48100223e-01,  1.09945057e+00,
         2.15989106e+00,  5.59653944e-01,  3.17429854e+00,
         4.18677241e-01,  1.61581498e+00,  8.22499215e-01,
         4.66512938e+00,  3.13212537e-01,  2.37469345e+00,
         6.15311846e-01,  1.20879155e+00,  6.85613903e+00,
         2.34314369e-01],
       [-1.39930194e+00, -1.65527083e+00,  2.31622368e+00,
         1.95804593e+00,  2.73992151e+00, -2.73989747e+00,
        -4.53531214e+00, -3.24109630e+00, -3.83397749e+00,
         3.83394386e+00,  7.50716987e+00,  4.53527236e+00,
         6.34627109e+00,  5.36489216e+00, -5.36484510e+00,
        -1.24263993e+01],
       [ 1.24494331e+00, -2.32578427e

In [20]:
X_t

array([[-6.27737625e-01,  6.02651255e-01, -3.78306868e-01,
         3.94054526e-01,  3.63188535e-01, -2.47362853e-01,
         2.18876026e-01,  2.37477455e-01, -2.27987109e-01,
         1.55278970e-01,  1.31905912e-01, -1.49073534e-01,
        -1.37396717e-01,  1.43116086e-01, -9.74744518e-02,
         7.94932634e-02],
       [-1.49157659e+00, -1.22679454e+00,  1.82985801e+00,
         2.22480071e+00,  1.50502483e+00, -3.31846066e+00,
        -1.84635624e+00, -2.72937336e+00, -2.24485981e+00,
         4.94973822e+00,  2.26509975e+00,  4.07106940e+00,
         2.75398174e+00,  3.34838033e+00, -7.38291364e+00,
        -2.77881200e+00],
       [ 6.36095438e-01, -6.55387875e-01, -4.16889237e-01,
         4.04617406e-01,  4.29533266e-01,  2.57375286e-01,
        -2.81510894e-01, -2.65181342e-01,  2.73224151e-01,
         1.63715245e-01,  1.84498827e-01, -1.68680642e-01,
        -1.79067796e-01,  1.73796636e-01,  1.04138521e-01,
        -1.20918294e-01],
       [ 1.13680896e+00, -7.28112359e

In [21]:
Y_r

array([0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 1., 0.])

In [22]:
Y_t

array([1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0.])

In [23]:
folds = 10

In [24]:
Kf = StratifiedKFold(n_splits=folds)

In [25]:
from sklearn.linear_model import LogisticRegression
def calc_fold(feats, X,Y, train_ix,valid_ix,C=1e12):
    """return error for train and validation sets"""
    reg = LogisticRegression(C=C, tol=1e-10, solver='liblinear')
    reg.fit(X[train_ix,:feats],Y[train_ix])
    prob = reg.predict_proba(X[:,:feats])[:,1]
    squares = (prob-Y)**2
    return np.mean(squares[train_ix]),np.mean(squares[valid_ix])

In [26]:
for feats in range(2,16):
    tr_err = va_err = 0
    for tr_ix,va_ix in Kf.split(Y_r,Y_r):
        r,v = calc_fold(feats,X_r,Y_r,tr_ix,va_ix)
        tr_err += r
        va_err += v
    print(feats,':',tr_err/folds, va_err/folds)

2 : 0.03836620866324905 0.056201400363455466
3 : 0.037866163674892976 0.06598179752364998
4 : 0.03759890428171919 0.06949218844974606
5 : 0.036824101799685406 0.07071656184963004
6 : 2.9613406091532e-19 0.04997944270689838
7 : 2.1630518233333717e-20 0.033298189019386235
8 : 1.8227258102824814e-20 0.016590417047554373
9 : 2.5305304810818608e-20 0.00037340572357543453
10 : 2.4770090578370503e-20 0.0006379004040787971
11 : 2.5725988135072247e-20 4.6307690102602506e-07
12 : 2.750916704259612e-20 6.510140095704939e-07
13 : 2.4108637558175518e-20 0.006539855593457766
14 : 2.245333234333628e-20 0.01128692133520354
15 : 3.35533253238226e-20 0.016454090327806595
